# Change these first
owner: chuckmac # Your GitHub username
repo: chuckmacdev-uptime # Your Github repository name

# Add your sites here
sites:
  - name: ChuckMacDev
    url: https://chuckmacdev.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  baseUrl: /chuckmacdev-uptime
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://chuckmacdev.com/img/logo-cmd-rev.png
  name: ChuckMacDev Upptime
  introTitle: Expert development
  introMessage: Uptime history for ChuckMacDev
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
